---
title: C28105 | Dokumentacja firmy Microsoft
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 5
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: 85bf74a1338ac227acd94f389eeb2a77ec086623
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 11/16/2018
ms.locfileid: "51750015"
---
# <a name="c28105"></a>C28105
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Ostrzeżenie C28105: Wyciek zasobów z powodu wyjątku  
  
 Podany zasób nie jest zwalniana, gdy wyjątek jest zgłaszany. Instrukcja określona przez ścieżkę może zgłosić wyjątek. To ostrzeżenie jest podobny do ostrzeżenie [C28103](../code-quality/c28103.md), z tą różnicą, że w tym przypadku chodzi o wyjątku.  
  
## <a name="example"></a>Przykład  
 Poniższy kod generuje to ostrzeżenie:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Poniższy kod pozwala uniknąć tego ostrzeżenia:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```



