---
title: C6312 | Dokumentacja firmy Microsoft
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: c2d627c4b8387e43b154ca6f2fb1d3ae334a70bd
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 11/16/2018
ms.locfileid: "51816765"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Ostrzeżenie C6312: możliwa nieskończona pętla: Użyj stałej EXCEPTION_CONTINUE_EXECUTION w wyrażeniu filtru wyjątków try-except  
  
 Ostrzeżenie to wskazuje na użycie stałej `EXCEPTION_CONTINUE_EXECUTION` (lub innej przeliczanej na -1) w wyrażeniu filtru obsługi wyjątków strukturalnych. Użyj wartości stałej `EXCEPTION_CONTINUE_EXECUTION` może prowadzić do wejścia w nieskończoną pętlę. Na przykład jeśli wyjątek został zgłoszony przez sprzęt, instrukcji, który spowodował wyjątek zostanie należy ponownie uruchomić. W przypadku nadal zły adres, który spowodował wyjątek, kolejny wyjątek wystąpi i być obsługiwane w taki sam sposób. Powoduje to nieskończoną pętlę.  
  
 Jawnym wywołaniem `RaiseException` zostanie bezpośrednio Przyczyna wejścia w nieskończoną pętlę, ale będzie wykonania kodu w bloku chronionym. Może to być nieoczekiwany i może prowadzić do pętli nieskończonej, jeżeli `RaiseException` był używany w celu uniknięcia dereferencji nieprawidłowego wskaźnika.  
  
 Zazwyczaj `EXCEPTION_CONTINUE_EXECUTION` powinny być zwracane tylko przez funkcję o nazwie w wyrażeniu filtru, który ma szansę, aby naprawić wskaźnika, który spowodował wyjątek albo podstawowa pamięć.  
  
## <a name="example"></a>Przykład  
 Poniższy kod generuje to ostrzeżenie:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Aby poprawić to ostrzeżenie, użyj następującego kodu:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```



